services:
  # Oracle XE Service
  oracle:
    image: gvenzl/oracle-xe:latest
    container_name: p3-oracle-1
    ports:
      - "1521:1521"
    environment:
      ORACLE_RANDOM_PASSWORD: "true"
      APP_USER: admin
      APP_USER_PASSWORD: admin
    volumes:
      - oracle-data:/ORCL
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  oracle-data: